name: Update Age

on:
#  schedule:
 #   - cron: '0 0 * * *'
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
        
      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "Github Actions Bot"

      - name: Update Age
        run: npm run update:age

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Has Changes?
        id: git-check
        run: |
          if [[ -n $(git diff HEAD) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - if: steps.git-check.outputs.changes == 'true'
        name: Commit & Push
        run: |
          git commit -am "Update Age on ${{ steps.date.outputs.date }}
          Co-Authored-By: Ahmed Abdelbaset <A7med3bdulBaset@gmail.com>
          "
          git pull
          git push

      - if: steps.git-check.outputs.changes == 'false'
        name: Already Up-to-date 
        run: echo "No changes to push"
